### ISSUE TITLE
Find some way of caching the stonk data

### ISSUE THREAD

**Issue by untangledwilliam** [stonks2midi/stonks2midi#20]
If we try to have more than 5 companies, then we will have to make more than 5 API requests, which is not allowed. So, we could either:

1. Make a list of companies which the user can choose from and hardcode all the different companies' data (which we get beforehand from the API) into an external file so that we don't have to call the API more than 5 times
2. The user chooses the four companies first, then the API request is made using just those four companies, and hopefully they will wait more than a minute before changing it again (maybe we could add a timer?)

If we have more companies, then the user is going to have to choose from them, which will require a GUI, so I might have to work with James to make a UI that works with the API data after I work out how to get the data.

**Comment by Horatio3** [comment]
lets get 7000 lines

**Comment by Horatio3** [comment]
https://cdn.ebaumsworld.com/thumbs/2019/06/18/014558/85992524/stonksmeme24.png

**Comment by Horatio3** [comment]
![image](https://user-images.githubusercontent.com/53750367/62689297-71781580-b9c2-11e9-8eb7-1473b2e05754.png)
